language: node_js
node_js:
    - "8.10.0"
addons:
  apt:
    packages:
    - cmake
    - srecord
    - ninja-build

script:
    - "wget -O gcc-arm.tar.bz2 https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2"
    - "tar -xaf gcc-arm.tar.bz2"
    - "export PATH=`pwd`/gcc-arm-none-eabi-7-2017-q4-major/bin:$PATH"
    - "npm install -g pxt"
    - "sudo pip install -U yotta"
    - "pxt target microbit"
    - "pxt install"
    - "pxt build"
    - "pxt test"
sudo: false
cache:
    directories:
    - npm_modules
    - pxt_modules