language: node_js
node_js:
    - "5.7.0"
script:
    - "npm install -g pxt"
    - "pxt target microbit"
    - "pxt install"
    - "pxt build"
    - "pxt test"
sudo: false
cache:
    directories:
    - npm_modules
    - pxt_modules